#!/usr/bin/env bash

# Check if exactly two arguments are provided
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <x> <y> <z>"
    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
    echo "y: A JSON file representing a trie tree"
    echo "z: A JSON file representing a trie tree"
    exit 1
fi

x=$1
y=$2
z=$3

# Check if x is either 0 or 1
if [ "$x" -eq 0 ]; then
    outfile="pat.json"
elif [ "$x" -eq 1 ]; then
    outfile="trie.json"
else
    echo "Error: x must be 0 or 1"
    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
    exit 1
fi

# Run the program
./tries 2 "$x" "$y" "$z" >"$outfile"
