#!/usr/bin/env bash

# Check if exactly two arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <x> <y>"
    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
    echo "y: A text file with one word per line"
    exit 1
fi

x=$1
y=$2

# Check if x is either 0 or 1
if [ "$x" -eq 0 ]; then
    inoutfile="pat.json"
elif [ "$x" -eq 1 ]; then
    inoutfile="trie.json"
else
    echo "Error: x must be 0 or 1"
    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
    exit 1
fi

# Run the program
./tries 1 "$x" "$inoutfile" <"$y"
