name: test
on: [push, pull_request, workflow_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: |
            build/
          key: ${{ runner.os }}-${{ runner.arch }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}
      - name: Run unit tests
        run: make test
      - uses: actions/upload-artifact@v4
        with:
          name: "test-artifact"
          path: |
            build/results/
